[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
tokio-native-tls = "0.3.1"
tokio-tungstenite = { version = "0.26.1", features = ["native-tls"]}
